### ISSUE TITLE
Currently the live website isn't fully functional due to dependencies being unable to load (or no longer existent on the cloud)

### ISSUE THREAD

**Issue by NinjaZMY** [Zev18/animeguide#1]
At first I tried a random link and it worked fine ( searched anime, accessed the anime link, where it loaded infos x the ability to write reviews etc...)

0) 
![image](https://github.com/user-attachments/assets/231a20f9-14d7-40e8-b813-18f82b2e1507)

1) 
![image](https://github.com/user-attachments/assets/a3576a0e-fd25-48f3-8101-112068b42aeb)

2) 
![image](https://github.com/user-attachments/assets/1c52a552-f11c-4de7-bae1-106f255eeede)

3) 
![image](https://github.com/user-attachments/assets/2e6e9aff-3563-4b99-88cd-54303bbba6d6)

4) 
![image](https://github.com/user-attachments/assets/0b58b2e6-feea-4a69-9def-1ed0d9370aea)

# above works fine
-
0) searching on discover
1) accessing a certain link page

and then I did a custom search, and after anime titles were loaded, I picked one of the anime to access it's page and that's when the errors below were manifested

Anime/website error link: https://animeguide.vercel.app/anime/54688
![image](https://github.com/user-attachments/assets/0097eca4-bd4d-419d-9950-88f18249f1a1)

![image](https://github.com/user-attachments/assets/87e53d06-9e35-4cb2-b8f5-97ed0851fcd5)

The following dependency is the one concerned: https://sgncomrfzmsccjmvvfpv.supabase.co/rest/v1/rpc/search_guides?offset=0&limit=11

if you fix this problem, the next thing you should work on, is probably to secure your links, as the error link isn't supposed to look like that, but if you consider that same link format to be secure then you're alright

**Comment by Zev18** [comment]
Dude this is an abandoned project. Never fully released and is not being maintained
